### ISSUE TITLE
Wallet Address - TypeError: Cannot read property 'ls' of undefined

### ISSUE THREAD

**Issue by JadTermsani** [filecoin-shipyard/js-filecoin-api-client#75]
When I run this command, `const addresses = await fc.wallet.addrs.ls()`
I get an error stating: **Cannot read property 'ls' of undefined**

node 10.16.0
filecoin-api-client 0.5.0

**Comment by alanshaw** [comment]
`wallet.addrs` was [removed from filecoin](https://github.com/filecoin-project/go-filecoin/pull/2295) a while ago
