### ISSUE TITLE
Payload updated for client.queryStorageDeal

### ISSUE THREAD

**Issue by mishmosh** [filecoin-shipyard/js-filecoin-api-client#78]
The endpoint for client.queryStorageDeal was added in #67.

Based on work in https://github.com/filecoin-project/go-filecoin/pull/3197, the response payload now includes 3 new fields: commD, commR, and commRStar.

@hazmatzo are there any changes needed in the endpoint itself, or tests, to support these changes?

**Comment by hazmatzo** [comment]
Hi @mishmosh! Let me check. For sure we should at least update the documentation and tests to ensure it's capturing what we're getting back, but let me double check what we're getting from the Go API. It may be that we also need to camelCase some of the keys when we get it back.

**Comment by hazmatzo** [comment]
No update needed, but I modified documentation and tests.

**Comment by mishmosh** [comment]
Awesome, I see that in https://github.com/filecoin-shipyard/js-filecoin-api-client/pull/79. Thanks!

cc @JadTermsani who brought up the question originally.

**Comment by alanshaw** [comment]
resolved in https://github.com/filecoin-shipyard/js-filecoin-api-client/pull/79
